//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemuFansBO.ServicioWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class ParseException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorOffsetField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorOffset {
            get {
                return this.errorOffsetField;
            }
            set {
                this.errorOffsetField = value;
                this.RaisePropertyChanged("errorOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class marca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_marcaField;
        
        private string descripcionField;
        
        private int idMarcaField;
        
        private bool idMarcaFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_marca {
            get {
                return this.codigo_marcaField;
            }
            set {
                this.codigo_marcaField = value;
                this.RaisePropertyChanged("codigo_marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idMarca {
            get {
                return this.idMarcaField;
            }
            set {
                this.idMarcaField = value;
                this.RaisePropertyChanged("idMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMarcaSpecified {
            get {
                return this.idMarcaFieldSpecified;
            }
            set {
                this.idMarcaFieldSpecified = value;
                this.RaisePropertyChanged("idMarcaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private estado estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private marca marcaField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estado estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public marca marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public enum estado {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class pedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private empleado empleadoField;
        
        private estadoPedido estado_pedidoField;
        
        private bool estado_pedidoFieldSpecified;
        
        private System.DateTime fecha_cancelacionField;
        
        private bool fecha_cancelacionFieldSpecified;
        
        private System.DateTime fecha_creacionField;
        
        private bool fecha_creacionFieldSpecified;
        
        private System.DateTime fecha_pagoField;
        
        private bool fecha_pagoFieldSpecified;
        
        private System.DateTime fecha_vencimientoField;
        
        private bool fecha_vencimientoFieldSpecified;
        
        private int id_pedidoField;
        
        private bool id_pedidoFieldSpecified;
        
        private double impuestosField;
        
        private double subtotalField;
        
        private tipoPedido tipo_pedidoField;
        
        private bool tipo_pedidoFieldSpecified;
        
        private double totalField;
        
        private usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoPedido estado_pedido {
            get {
                return this.estado_pedidoField;
            }
            set {
                this.estado_pedidoField = value;
                this.RaisePropertyChanged("estado_pedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estado_pedidoSpecified {
            get {
                return this.estado_pedidoFieldSpecified;
            }
            set {
                this.estado_pedidoFieldSpecified = value;
                this.RaisePropertyChanged("estado_pedidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha_cancelacion {
            get {
                return this.fecha_cancelacionField;
            }
            set {
                this.fecha_cancelacionField = value;
                this.RaisePropertyChanged("fecha_cancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_cancelacionSpecified {
            get {
                return this.fecha_cancelacionFieldSpecified;
            }
            set {
                this.fecha_cancelacionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_cancelacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                this.fecha_creacionField = value;
                this.RaisePropertyChanged("fecha_creacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_creacionSpecified {
            get {
                return this.fecha_creacionFieldSpecified;
            }
            set {
                this.fecha_creacionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_creacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fecha_pago {
            get {
                return this.fecha_pagoField;
            }
            set {
                this.fecha_pagoField = value;
                this.RaisePropertyChanged("fecha_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_pagoSpecified {
            get {
                return this.fecha_pagoFieldSpecified;
            }
            set {
                this.fecha_pagoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_pagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fecha_vencimiento {
            get {
                return this.fecha_vencimientoField;
            }
            set {
                this.fecha_vencimientoField = value;
                this.RaisePropertyChanged("fecha_vencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_vencimientoSpecified {
            get {
                return this.fecha_vencimientoFieldSpecified;
            }
            set {
                this.fecha_vencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_vencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int id_pedido {
            get {
                return this.id_pedidoField;
            }
            set {
                this.id_pedidoField = value;
                this.RaisePropertyChanged("id_pedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_pedidoSpecified {
            get {
                return this.id_pedidoFieldSpecified;
            }
            set {
                this.id_pedidoFieldSpecified = value;
                this.RaisePropertyChanged("id_pedidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double impuestos {
            get {
                return this.impuestosField;
            }
            set {
                this.impuestosField = value;
                this.RaisePropertyChanged("impuestos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public tipoPedido tipo_pedido {
            get {
                return this.tipo_pedidoField;
            }
            set {
                this.tipo_pedidoField = value;
                this.RaisePropertyChanged("tipo_pedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_pedidoSpecified {
            get {
                return this.tipo_pedidoFieldSpecified;
            }
            set {
                this.tipo_pedidoFieldSpecified = value;
                this.RaisePropertyChanged("tipo_pedidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class empleado : usuario {
        
        private string codigoField;
        
        private int idEmpleadoField;
        
        private bool idEmpleadoFieldSpecified;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEmpleadoSpecified {
            get {
                return this.idEmpleadoFieldSpecified;
            }
            set {
                this.idEmpleadoFieldSpecified = value;
                this.RaisePropertyChanged("idEmpleadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string doiField;
        
        private System.DateTime fecha_registroField;
        
        private bool fecha_registroFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private string telefonoField;
        
        private tipoDoi tipo_doiField;
        
        private bool tipo_doiFieldSpecified;
        
        private tipoUsuario tipo_usuarioField;
        
        private bool tipo_usuarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string doi {
            get {
                return this.doiField;
            }
            set {
                this.doiField = value;
                this.RaisePropertyChanged("doi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                this.fecha_registroField = value;
                this.RaisePropertyChanged("fecha_registro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_registroSpecified {
            get {
                return this.fecha_registroFieldSpecified;
            }
            set {
                this.fecha_registroFieldSpecified = value;
                this.RaisePropertyChanged("fecha_registroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoDoi tipo_doi {
            get {
                return this.tipo_doiField;
            }
            set {
                this.tipo_doiField = value;
                this.RaisePropertyChanged("tipo_doi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_doiSpecified {
            get {
                return this.tipo_doiFieldSpecified;
            }
            set {
                this.tipo_doiFieldSpecified = value;
                this.RaisePropertyChanged("tipo_doiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoUsuario tipo_usuario {
            get {
                return this.tipo_usuarioField;
            }
            set {
                this.tipo_usuarioField = value;
                this.RaisePropertyChanged("tipo_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_usuarioSpecified {
            get {
                return this.tipo_usuarioFieldSpecified;
            }
            set {
                this.tipo_usuarioFieldSpecified = value;
                this.RaisePropertyChanged("tipo_usuarioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public enum tipoDoi {
        
        /// <remarks/>
        PASAPORTE,
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        RUC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        EMPRESA,
        
        /// <remarks/>
        PROVEEDOR,
        
        /// <remarks/>
        EMPLEADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class cliente : usuario {
        
        private string codigoField;
        
        private int idClienteField;
        
        private bool idClienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public enum estadoPedido {
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        PAGADO,
        
        /// <remarks/>
        PENDIENTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public enum tipoPedido {
        
        /// <remarks/>
        COMPRA,
        
        /// <remarks/>
        VENTA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class detallePedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int cantidad_por_entregarField;
        
        private bool cantidad_por_entregarFieldSpecified;
        
        private string codigoField;
        
        private string descripcionField;
        
        private double montoField;
        
        private pedido pedidoField;
        
        private producto productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad_por_entregar {
            get {
                return this.cantidad_por_entregarField;
            }
            set {
                this.cantidad_por_entregarField = value;
                this.RaisePropertyChanged("cantidad_por_entregar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidad_por_entregarSpecified {
            get {
                return this.cantidad_por_entregarFieldSpecified;
            }
            set {
                this.cantidad_por_entregarFieldSpecified = value;
                this.RaisePropertyChanged("cantidad_por_entregarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public pedido pedido {
            get {
                return this.pedidoField;
            }
            set {
                this.pedidoField = value;
                this.RaisePropertyChanged("pedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class resumenPorFecha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantPedidosField;
        
        private bool cantPedidosFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantPedidos {
            get {
                return this.cantPedidosField;
            }
            set {
                this.cantPedidosField = value;
                this.RaisePropertyChanged("cantPedidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantPedidosSpecified {
            get {
                return this.cantPedidosFieldSpecified;
            }
            set {
                this.cantPedidosFieldSpecified = value;
                this.RaisePropertyChanged("cantPedidosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", ConfigurationName="ServicioWS.ServicioWS")]
    public interface ServicioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse cliente_listarClientesNombreCodigo(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse> cliente_listarClientesNombreCodigoAsync(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.helloResponse hello(TemuFansBO.ServicioWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.helloResponse> helloAsync(TemuFansBO.ServicioWS.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.cliente_listarClientesResponse cliente_listarClientes(TemuFansBO.ServicioWS.cliente_listarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesResponse> cliente_listarClientesAsync(TemuFansBO.ServicioWS.cliente_listarClientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_listar_fechaRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_listar_fechaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.pedido_listar_fechaResponse pedido_listar_fecha(TemuFansBO.ServicioWS.pedido_listar_fechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_listar_fechaRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_listar_fechaResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_listar_fechaResponse> pedido_listar_fechaAsync(TemuFansBO.ServicioWS.pedido_listar_fechaRequest request);
        
        // CODEGEN: El parámetro 'idPedido' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TemuFansBO.ServicioWS.pedido_modificarPagoResponse pedido_modificarPago(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_modificarPagoResponse> pedido_modificarPagoAsync(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/detallePedido_obtenerLineasPedid" +
            "oRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/detallePedido_obtenerLineasPedid" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoResponse detallePedido_obtenerLineasPedido(TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/detallePedido_obtenerLineasPedid" +
            "oRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/detallePedido_obtenerLineasPedid" +
            "oResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoResponse> detallePedido_obtenerLineasPedidoAsync(TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(TemuFansBO.ServicioWS.ParseException), Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_cliente/Fault/P" +
            "arseException", Name="ParseException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.usuario_insertar_clienteResponse usuario_insertar_cliente(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteResponse" +
            "")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.usuario_insertar_clienteResponse> usuario_insertar_clienteAsync(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request);
        
        // CODEGEN: El parámetro 'idProducto' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_eliminarProductoRequest" +
            "", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_eliminarProductoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TemuFansBO.ServicioWS.producto_eliminarProductoResponse producto_eliminarProducto(TemuFansBO.ServicioWS.producto_eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_eliminarProductoRequest" +
            "", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_eliminarProductoRespons" +
            "e")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_eliminarProductoResponse> producto_eliminarProductoAsync(TemuFansBO.ServicioWS.producto_eliminarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_insertarProductoRequest" +
            "", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_insertarProductoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.producto_insertarProductoResponse producto_insertarProducto(TemuFansBO.ServicioWS.producto_insertarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_insertarProductoRequest" +
            "", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_insertarProductoRespons" +
            "e")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_insertarProductoResponse> producto_insertarProductoAsync(TemuFansBO.ServicioWS.producto_insertarProductoRequest request);
        
        // CODEGEN: El parámetro 'idProducto' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_modificarProductoReques" +
            "t", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_modificarProductoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TemuFansBO.ServicioWS.producto_modificarProductoResponse producto_modificarProducto(TemuFansBO.ServicioWS.producto_modificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_modificarProductoReques" +
            "t", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/producto_modificarProductoRespon" +
            "se")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_modificarProductoResponse> producto_modificarProductoAsync(TemuFansBO.ServicioWS.producto_modificarProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientesNombreCodigo", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesNombreCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        public cliente_listarClientesNombreCodigoRequest() {
        }
        
        public cliente_listarClientesNombreCodigoRequest(string nombre, string codigo) {
            this.nombre = nombre;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientesNombreCodigoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesNombreCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemuFansBO.ServicioWS.cliente[] @return;
        
        public cliente_listarClientesNombreCodigoResponse() {
        }
        
        public cliente_listarClientesNombreCodigoResponse(TemuFansBO.ServicioWS.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientes", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesRequest {
        
        public cliente_listarClientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientesResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemuFansBO.ServicioWS.cliente[] @return;
        
        public cliente_listarClientesResponse() {
        }
        
        public cliente_listarClientesResponse(TemuFansBO.ServicioWS.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pedido_listar_fecha", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class pedido_listar_fechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        public pedido_listar_fechaRequest() {
        }
        
        public pedido_listar_fechaRequest(string fechaInicio, string fechaFin) {
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pedido_listar_fechaResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class pedido_listar_fechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemuFansBO.ServicioWS.resumenPorFecha[] @return;
        
        public pedido_listar_fechaResponse() {
        }
        
        public pedido_listar_fechaResponse(TemuFansBO.ServicioWS.resumenPorFecha[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pedido_modificarPago", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class pedido_modificarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado_pedido;
        
        public pedido_modificarPagoRequest() {
        }
        
        public pedido_modificarPagoRequest(int idPedido, string estado_pedido) {
            this.idPedido = idPedido;
            this.estado_pedido = estado_pedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pedido_modificarPagoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class pedido_modificarPagoResponse {
        
        public pedido_modificarPagoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detallePedido_obtenerLineasPedido", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class detallePedido_obtenerLineasPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public detallePedido_obtenerLineasPedidoRequest() {
        }
        
        public detallePedido_obtenerLineasPedidoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="detallePedido_obtenerLineasPedidoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class detallePedido_obtenerLineasPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemuFansBO.ServicioWS.detallePedido[] @return;
        
        public detallePedido_obtenerLineasPedidoResponse() {
        }
        
        public detallePedido_obtenerLineasPedidoResponse(TemuFansBO.ServicioWS.detallePedido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="usuario_insertar_cliente", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class usuario_insertar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo_usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string doi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo_doi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_registro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        public usuario_insertar_clienteRequest() {
        }
        
        public usuario_insertar_clienteRequest(string tipo_usuario, string doi, string tipo_doi, string correo, string fecha_registro, string nombre, string telefono) {
            this.tipo_usuario = tipo_usuario;
            this.doi = doi;
            this.tipo_doi = tipo_doi;
            this.correo = correo;
            this.fecha_registro = fecha_registro;
            this.nombre = nombre;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="usuario_insertar_clienteResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class usuario_insertar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public usuario_insertar_clienteResponse() {
        }
        
        public usuario_insertar_clienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="producto_eliminarProducto", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class producto_eliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public producto_eliminarProductoRequest() {
        }
        
        public producto_eliminarProductoRequest(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="producto_eliminarProductoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class producto_eliminarProductoResponse {
        
        public producto_eliminarProductoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="producto_insertarProducto", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class producto_insertarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMarca;
        
        public producto_insertarProductoRequest() {
        }
        
        public producto_insertarProductoRequest(double precio, string nombre, string estado, int idMarca) {
            this.precio = precio;
            this.nombre = nombre;
            this.estado = estado;
            this.idMarca = idMarca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="producto_insertarProductoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class producto_insertarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public producto_insertarProductoResponse() {
        }
        
        public producto_insertarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="producto_modificarProducto", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class producto_modificarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio;
        
        public producto_modificarProductoRequest() {
        }
        
        public producto_modificarProductoRequest(int idProducto, string nombre, string estado, double precio) {
            this.idProducto = idProducto;
            this.nombre = nombre;
            this.estado = estado;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="producto_modificarProductoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class producto_modificarProductoResponse {
        
        public producto_modificarProductoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWSChannel : TemuFansBO.ServicioWS.ServicioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWSClient : System.ServiceModel.ClientBase<TemuFansBO.ServicioWS.ServicioWS>, TemuFansBO.ServicioWS.ServicioWS {
        
        public ServicioWSClient() {
        }
        
        public ServicioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientesNombreCodigo(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request) {
            return base.Channel.cliente_listarClientesNombreCodigo(request);
        }
        
        public TemuFansBO.ServicioWS.cliente[] cliente_listarClientesNombreCodigo(string nombre, string codigo) {
            TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest();
            inValue.nombre = nombre;
            inValue.codigo = codigo;
            TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientesNombreCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse> TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientesNombreCodigoAsync(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request) {
            return base.Channel.cliente_listarClientesNombreCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse> cliente_listarClientesNombreCodigoAsync(string nombre, string codigo) {
            TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest();
            inValue.nombre = nombre;
            inValue.codigo = codigo;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientesNombreCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.helloResponse TemuFansBO.ServicioWS.ServicioWS.hello(TemuFansBO.ServicioWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            TemuFansBO.ServicioWS.helloRequest inValue = new TemuFansBO.ServicioWS.helloRequest();
            inValue.name = name;
            TemuFansBO.ServicioWS.helloResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.helloResponse> TemuFansBO.ServicioWS.ServicioWS.helloAsync(TemuFansBO.ServicioWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.helloResponse> helloAsync(string name) {
            TemuFansBO.ServicioWS.helloRequest inValue = new TemuFansBO.ServicioWS.helloRequest();
            inValue.name = name;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.cliente_listarClientesResponse TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientes(TemuFansBO.ServicioWS.cliente_listarClientesRequest request) {
            return base.Channel.cliente_listarClientes(request);
        }
        
        public TemuFansBO.ServicioWS.cliente[] cliente_listarClientes() {
            TemuFansBO.ServicioWS.cliente_listarClientesRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesRequest();
            TemuFansBO.ServicioWS.cliente_listarClientesResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesResponse> TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientesAsync(TemuFansBO.ServicioWS.cliente_listarClientesRequest request) {
            return base.Channel.cliente_listarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesResponse> cliente_listarClientesAsync() {
            TemuFansBO.ServicioWS.cliente_listarClientesRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesRequest();
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.pedido_listar_fechaResponse TemuFansBO.ServicioWS.ServicioWS.pedido_listar_fecha(TemuFansBO.ServicioWS.pedido_listar_fechaRequest request) {
            return base.Channel.pedido_listar_fecha(request);
        }
        
        public TemuFansBO.ServicioWS.resumenPorFecha[] pedido_listar_fecha(string fechaInicio, string fechaFin) {
            TemuFansBO.ServicioWS.pedido_listar_fechaRequest inValue = new TemuFansBO.ServicioWS.pedido_listar_fechaRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            TemuFansBO.ServicioWS.pedido_listar_fechaResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).pedido_listar_fecha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_listar_fechaResponse> TemuFansBO.ServicioWS.ServicioWS.pedido_listar_fechaAsync(TemuFansBO.ServicioWS.pedido_listar_fechaRequest request) {
            return base.Channel.pedido_listar_fechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_listar_fechaResponse> pedido_listar_fechaAsync(string fechaInicio, string fechaFin) {
            TemuFansBO.ServicioWS.pedido_listar_fechaRequest inValue = new TemuFansBO.ServicioWS.pedido_listar_fechaRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).pedido_listar_fechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.pedido_modificarPagoResponse TemuFansBO.ServicioWS.ServicioWS.pedido_modificarPago(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request) {
            return base.Channel.pedido_modificarPago(request);
        }
        
        public void pedido_modificarPago(int idPedido, string estado_pedido) {
            TemuFansBO.ServicioWS.pedido_modificarPagoRequest inValue = new TemuFansBO.ServicioWS.pedido_modificarPagoRequest();
            inValue.idPedido = idPedido;
            inValue.estado_pedido = estado_pedido;
            TemuFansBO.ServicioWS.pedido_modificarPagoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).pedido_modificarPago(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_modificarPagoResponse> TemuFansBO.ServicioWS.ServicioWS.pedido_modificarPagoAsync(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request) {
            return base.Channel.pedido_modificarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_modificarPagoResponse> pedido_modificarPagoAsync(int idPedido, string estado_pedido) {
            TemuFansBO.ServicioWS.pedido_modificarPagoRequest inValue = new TemuFansBO.ServicioWS.pedido_modificarPagoRequest();
            inValue.idPedido = idPedido;
            inValue.estado_pedido = estado_pedido;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).pedido_modificarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoResponse TemuFansBO.ServicioWS.ServicioWS.detallePedido_obtenerLineasPedido(TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest request) {
            return base.Channel.detallePedido_obtenerLineasPedido(request);
        }
        
        public TemuFansBO.ServicioWS.detallePedido[] detallePedido_obtenerLineasPedido(int id) {
            TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest inValue = new TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest();
            inValue.id = id;
            TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).detallePedido_obtenerLineasPedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoResponse> TemuFansBO.ServicioWS.ServicioWS.detallePedido_obtenerLineasPedidoAsync(TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest request) {
            return base.Channel.detallePedido_obtenerLineasPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoResponse> detallePedido_obtenerLineasPedidoAsync(int id) {
            TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest inValue = new TemuFansBO.ServicioWS.detallePedido_obtenerLineasPedidoRequest();
            inValue.id = id;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).detallePedido_obtenerLineasPedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.usuario_insertar_clienteResponse TemuFansBO.ServicioWS.ServicioWS.usuario_insertar_cliente(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request) {
            return base.Channel.usuario_insertar_cliente(request);
        }
        
        public int usuario_insertar_cliente(string tipo_usuario, string doi, string tipo_doi, string correo, string fecha_registro, string nombre, string telefono) {
            TemuFansBO.ServicioWS.usuario_insertar_clienteRequest inValue = new TemuFansBO.ServicioWS.usuario_insertar_clienteRequest();
            inValue.tipo_usuario = tipo_usuario;
            inValue.doi = doi;
            inValue.tipo_doi = tipo_doi;
            inValue.correo = correo;
            inValue.fecha_registro = fecha_registro;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            TemuFansBO.ServicioWS.usuario_insertar_clienteResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).usuario_insertar_cliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.usuario_insertar_clienteResponse> TemuFansBO.ServicioWS.ServicioWS.usuario_insertar_clienteAsync(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request) {
            return base.Channel.usuario_insertar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.usuario_insertar_clienteResponse> usuario_insertar_clienteAsync(string tipo_usuario, string doi, string tipo_doi, string correo, string fecha_registro, string nombre, string telefono) {
            TemuFansBO.ServicioWS.usuario_insertar_clienteRequest inValue = new TemuFansBO.ServicioWS.usuario_insertar_clienteRequest();
            inValue.tipo_usuario = tipo_usuario;
            inValue.doi = doi;
            inValue.tipo_doi = tipo_doi;
            inValue.correo = correo;
            inValue.fecha_registro = fecha_registro;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).usuario_insertar_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.producto_eliminarProductoResponse TemuFansBO.ServicioWS.ServicioWS.producto_eliminarProducto(TemuFansBO.ServicioWS.producto_eliminarProductoRequest request) {
            return base.Channel.producto_eliminarProducto(request);
        }
        
        public void producto_eliminarProducto(int idProducto) {
            TemuFansBO.ServicioWS.producto_eliminarProductoRequest inValue = new TemuFansBO.ServicioWS.producto_eliminarProductoRequest();
            inValue.idProducto = idProducto;
            TemuFansBO.ServicioWS.producto_eliminarProductoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).producto_eliminarProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_eliminarProductoResponse> TemuFansBO.ServicioWS.ServicioWS.producto_eliminarProductoAsync(TemuFansBO.ServicioWS.producto_eliminarProductoRequest request) {
            return base.Channel.producto_eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_eliminarProductoResponse> producto_eliminarProductoAsync(int idProducto) {
            TemuFansBO.ServicioWS.producto_eliminarProductoRequest inValue = new TemuFansBO.ServicioWS.producto_eliminarProductoRequest();
            inValue.idProducto = idProducto;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).producto_eliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.producto_insertarProductoResponse TemuFansBO.ServicioWS.ServicioWS.producto_insertarProducto(TemuFansBO.ServicioWS.producto_insertarProductoRequest request) {
            return base.Channel.producto_insertarProducto(request);
        }
        
        public int producto_insertarProducto(double precio, string nombre, string estado, int idMarca) {
            TemuFansBO.ServicioWS.producto_insertarProductoRequest inValue = new TemuFansBO.ServicioWS.producto_insertarProductoRequest();
            inValue.precio = precio;
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.idMarca = idMarca;
            TemuFansBO.ServicioWS.producto_insertarProductoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).producto_insertarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_insertarProductoResponse> TemuFansBO.ServicioWS.ServicioWS.producto_insertarProductoAsync(TemuFansBO.ServicioWS.producto_insertarProductoRequest request) {
            return base.Channel.producto_insertarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_insertarProductoResponse> producto_insertarProductoAsync(double precio, string nombre, string estado, int idMarca) {
            TemuFansBO.ServicioWS.producto_insertarProductoRequest inValue = new TemuFansBO.ServicioWS.producto_insertarProductoRequest();
            inValue.precio = precio;
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.idMarca = idMarca;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).producto_insertarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.producto_modificarProductoResponse TemuFansBO.ServicioWS.ServicioWS.producto_modificarProducto(TemuFansBO.ServicioWS.producto_modificarProductoRequest request) {
            return base.Channel.producto_modificarProducto(request);
        }
        
        public void producto_modificarProducto(int idProducto, string nombre, string estado, double precio) {
            TemuFansBO.ServicioWS.producto_modificarProductoRequest inValue = new TemuFansBO.ServicioWS.producto_modificarProductoRequest();
            inValue.idProducto = idProducto;
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.precio = precio;
            TemuFansBO.ServicioWS.producto_modificarProductoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).producto_modificarProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_modificarProductoResponse> TemuFansBO.ServicioWS.ServicioWS.producto_modificarProductoAsync(TemuFansBO.ServicioWS.producto_modificarProductoRequest request) {
            return base.Channel.producto_modificarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.producto_modificarProductoResponse> producto_modificarProductoAsync(int idProducto, string nombre, string estado, double precio) {
            TemuFansBO.ServicioWS.producto_modificarProductoRequest inValue = new TemuFansBO.ServicioWS.producto_modificarProductoRequest();
            inValue.idProducto = idProducto;
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.precio = precio;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).producto_modificarProductoAsync(inValue);
        }
    }
}
