//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemuFansBO.ServicioWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class ParseException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorOffsetField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorOffset {
            get {
                return this.errorOffsetField;
            }
            set {
                this.errorOffsetField = value;
                this.RaisePropertyChanged("errorOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string doiField;
        
        private System.DateTime fecha_registroField;
        
        private bool fecha_registroFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombreField;
        
        private string telefonoField;
        
        private tipoDoi tipo_doiField;
        
        private bool tipo_doiFieldSpecified;
        
        private tipoUsuario tipo_usuarioField;
        
        private bool tipo_usuarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string doi {
            get {
                return this.doiField;
            }
            set {
                this.doiField = value;
                this.RaisePropertyChanged("doi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                this.fecha_registroField = value;
                this.RaisePropertyChanged("fecha_registro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_registroSpecified {
            get {
                return this.fecha_registroFieldSpecified;
            }
            set {
                this.fecha_registroFieldSpecified = value;
                this.RaisePropertyChanged("fecha_registroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoDoi tipo_doi {
            get {
                return this.tipo_doiField;
            }
            set {
                this.tipo_doiField = value;
                this.RaisePropertyChanged("tipo_doi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_doiSpecified {
            get {
                return this.tipo_doiFieldSpecified;
            }
            set {
                this.tipo_doiFieldSpecified = value;
                this.RaisePropertyChanged("tipo_doiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoUsuario tipo_usuario {
            get {
                return this.tipo_usuarioField;
            }
            set {
                this.tipo_usuarioField = value;
                this.RaisePropertyChanged("tipo_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_usuarioSpecified {
            get {
                return this.tipo_usuarioFieldSpecified;
            }
            set {
                this.tipo_usuarioFieldSpecified = value;
                this.RaisePropertyChanged("tipo_usuarioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public enum tipoDoi {
        
        /// <remarks/>
        PASAPORTE,
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        RUC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        EMPRESA,
        
        /// <remarks/>
        PROVEEDOR,
        
        /// <remarks/>
        EMPLEADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/")]
    public partial class cliente : usuario {
        
        private string codigoField;
        
        private int idClienteField;
        
        private bool idClienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", ConfigurationName="ServicioWS.ServicioWS")]
    public interface ServicioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.helloResponse hello(TemuFansBO.ServicioWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/helloResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.helloResponse> helloAsync(TemuFansBO.ServicioWS.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.cliente_listarClientesResponse cliente_listarClientes(TemuFansBO.ServicioWS.cliente_listarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesResponse> cliente_listarClientesAsync(TemuFansBO.ServicioWS.cliente_listarClientesRequest request);
        
        // CODEGEN: El parámetro 'idPedido' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        TemuFansBO.ServicioWS.pedido_modificarPagoResponse pedido_modificarPago(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/pedido_modificarPagoResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_modificarPagoResponse> pedido_modificarPagoAsync(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(TemuFansBO.ServicioWS.ParseException), Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_cliente/Fault/P" +
            "arseException", Name="ParseException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.usuario_insertar_clienteResponse usuario_insertar_cliente(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/usuario_insertar_clienteResponse" +
            "")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.usuario_insertar_clienteResponse> usuario_insertar_clienteAsync(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse cliente_listarClientesNombreCodigo(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goRequest", ReplyAction="http://servicios.TemuFans.pucp.edu.pe/ServicioWS/cliente_listarClientesNombreCodi" +
            "goResponse")]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse> cliente_listarClientesNombreCodigoAsync(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientes", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesRequest {
        
        public cliente_listarClientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientesResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemuFansBO.ServicioWS.cliente[] @return;
        
        public cliente_listarClientesResponse() {
        }
        
        public cliente_listarClientesResponse(TemuFansBO.ServicioWS.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pedido_modificarPago", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class pedido_modificarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado_pedido;
        
        public pedido_modificarPagoRequest() {
        }
        
        public pedido_modificarPagoRequest(int idPedido, string estado_pedido) {
            this.idPedido = idPedido;
            this.estado_pedido = estado_pedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pedido_modificarPagoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class pedido_modificarPagoResponse {
        
        public pedido_modificarPagoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="usuario_insertar_cliente", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class usuario_insertar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo_usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string doi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo_doi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_registro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        public usuario_insertar_clienteRequest() {
        }
        
        public usuario_insertar_clienteRequest(string tipo_usuario, string doi, string tipo_doi, string correo, string fecha_registro, string nombre, string telefono) {
            this.tipo_usuario = tipo_usuario;
            this.doi = doi;
            this.tipo_doi = tipo_doi;
            this.correo = correo;
            this.fecha_registro = fecha_registro;
            this.nombre = nombre;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="usuario_insertar_clienteResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class usuario_insertar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public usuario_insertar_clienteResponse() {
        }
        
        public usuario_insertar_clienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientesNombreCodigo", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesNombreCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        public cliente_listarClientesNombreCodigoRequest() {
        }
        
        public cliente_listarClientesNombreCodigoRequest(string nombre, string codigo) {
            this.nombre = nombre;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarClientesNombreCodigoResponse", WrapperNamespace="http://servicios.TemuFans.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarClientesNombreCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.TemuFans.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemuFansBO.ServicioWS.cliente[] @return;
        
        public cliente_listarClientesNombreCodigoResponse() {
        }
        
        public cliente_listarClientesNombreCodigoResponse(TemuFansBO.ServicioWS.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWSChannel : TemuFansBO.ServicioWS.ServicioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWSClient : System.ServiceModel.ClientBase<TemuFansBO.ServicioWS.ServicioWS>, TemuFansBO.ServicioWS.ServicioWS {
        
        public ServicioWSClient() {
        }
        
        public ServicioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.helloResponse TemuFansBO.ServicioWS.ServicioWS.hello(TemuFansBO.ServicioWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            TemuFansBO.ServicioWS.helloRequest inValue = new TemuFansBO.ServicioWS.helloRequest();
            inValue.name = name;
            TemuFansBO.ServicioWS.helloResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.helloResponse> TemuFansBO.ServicioWS.ServicioWS.helloAsync(TemuFansBO.ServicioWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.helloResponse> helloAsync(string name) {
            TemuFansBO.ServicioWS.helloRequest inValue = new TemuFansBO.ServicioWS.helloRequest();
            inValue.name = name;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.cliente_listarClientesResponse TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientes(TemuFansBO.ServicioWS.cliente_listarClientesRequest request) {
            return base.Channel.cliente_listarClientes(request);
        }
        
        public TemuFansBO.ServicioWS.cliente[] cliente_listarClientes() {
            TemuFansBO.ServicioWS.cliente_listarClientesRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesRequest();
            TemuFansBO.ServicioWS.cliente_listarClientesResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesResponse> TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientesAsync(TemuFansBO.ServicioWS.cliente_listarClientesRequest request) {
            return base.Channel.cliente_listarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesResponse> cliente_listarClientesAsync() {
            TemuFansBO.ServicioWS.cliente_listarClientesRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesRequest();
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.pedido_modificarPagoResponse TemuFansBO.ServicioWS.ServicioWS.pedido_modificarPago(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request) {
            return base.Channel.pedido_modificarPago(request);
        }
        
        public void pedido_modificarPago(int idPedido, string estado_pedido) {
            TemuFansBO.ServicioWS.pedido_modificarPagoRequest inValue = new TemuFansBO.ServicioWS.pedido_modificarPagoRequest();
            inValue.idPedido = idPedido;
            inValue.estado_pedido = estado_pedido;
            TemuFansBO.ServicioWS.pedido_modificarPagoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).pedido_modificarPago(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_modificarPagoResponse> TemuFansBO.ServicioWS.ServicioWS.pedido_modificarPagoAsync(TemuFansBO.ServicioWS.pedido_modificarPagoRequest request) {
            return base.Channel.pedido_modificarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.pedido_modificarPagoResponse> pedido_modificarPagoAsync(int idPedido, string estado_pedido) {
            TemuFansBO.ServicioWS.pedido_modificarPagoRequest inValue = new TemuFansBO.ServicioWS.pedido_modificarPagoRequest();
            inValue.idPedido = idPedido;
            inValue.estado_pedido = estado_pedido;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).pedido_modificarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.usuario_insertar_clienteResponse TemuFansBO.ServicioWS.ServicioWS.usuario_insertar_cliente(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request) {
            return base.Channel.usuario_insertar_cliente(request);
        }
        
        public int usuario_insertar_cliente(string tipo_usuario, string doi, string tipo_doi, string correo, string fecha_registro, string nombre, string telefono) {
            TemuFansBO.ServicioWS.usuario_insertar_clienteRequest inValue = new TemuFansBO.ServicioWS.usuario_insertar_clienteRequest();
            inValue.tipo_usuario = tipo_usuario;
            inValue.doi = doi;
            inValue.tipo_doi = tipo_doi;
            inValue.correo = correo;
            inValue.fecha_registro = fecha_registro;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            TemuFansBO.ServicioWS.usuario_insertar_clienteResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).usuario_insertar_cliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.usuario_insertar_clienteResponse> TemuFansBO.ServicioWS.ServicioWS.usuario_insertar_clienteAsync(TemuFansBO.ServicioWS.usuario_insertar_clienteRequest request) {
            return base.Channel.usuario_insertar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.usuario_insertar_clienteResponse> usuario_insertar_clienteAsync(string tipo_usuario, string doi, string tipo_doi, string correo, string fecha_registro, string nombre, string telefono) {
            TemuFansBO.ServicioWS.usuario_insertar_clienteRequest inValue = new TemuFansBO.ServicioWS.usuario_insertar_clienteRequest();
            inValue.tipo_usuario = tipo_usuario;
            inValue.doi = doi;
            inValue.tipo_doi = tipo_doi;
            inValue.correo = correo;
            inValue.fecha_registro = fecha_registro;
            inValue.nombre = nombre;
            inValue.telefono = telefono;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).usuario_insertar_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientesNombreCodigo(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request) {
            return base.Channel.cliente_listarClientesNombreCodigo(request);
        }
        
        public TemuFansBO.ServicioWS.cliente[] cliente_listarClientesNombreCodigo(string nombre, string codigo) {
            TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest();
            inValue.nombre = nombre;
            inValue.codigo = codigo;
            TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse retVal = ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientesNombreCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse> TemuFansBO.ServicioWS.ServicioWS.cliente_listarClientesNombreCodigoAsync(TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest request) {
            return base.Channel.cliente_listarClientesNombreCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoResponse> cliente_listarClientesNombreCodigoAsync(string nombre, string codigo) {
            TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest inValue = new TemuFansBO.ServicioWS.cliente_listarClientesNombreCodigoRequest();
            inValue.nombre = nombre;
            inValue.codigo = codigo;
            return ((TemuFansBO.ServicioWS.ServicioWS)(this)).cliente_listarClientesNombreCodigoAsync(inValue);
        }
    }
}
